### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/ETTh1/var_scaler_info.npz'

### ISSUE THREAD

**Issue by hexiangdong2020** [2448845600/KAN4TSF#1]
When I run the following command as per README:
`python train.py -c config/reproduce_conf/DLinear/96for96.py`
I got this error:
`FileNotFoundError: [Errno 2] No such file or directory: '/home/deeprob/KAN4TSF/config/reproduce_conf/DLinear/96for96.py'`
Then, I change the config filepath to "config/ETTh1_RLinear/96for96.py".
I got this error:
`FileNotFoundError: [Errno 2] No such file or directory: 'dataset/ETTh1/var_scaler_info.npz'`
I tried to find online ETT datasets, for example: “https://github.com/zhouhaoyi/ETDataset/tree/main”.
But it does not contain this npz file.
You said in ReadMe: "ETT can be downloaded within this project, and other datasets will be released soon."
I hope you will be able to provide a working version soon.

**Comment by smilehanCN** [comment]
I will update this project before the end of next week, provide the dataset download link and update the experimental configuration. Please wait for a while.

**Comment by ChineseDictionary** [comment]
期待更新和完善！

**Comment by lunaaa95** [comment]
same question. Hope for quick update.

**Comment by hexiangdong2020** [comment]
When I deleted these codes:
`stat = np.load(os.path.join(self.hparams.data_root, self.hparams.dataset_name, 'var_scaler_info.npz'))
self.register_buffer('mean', torch.tensor(stat['mean']).float())
self.register_buffer('std', torch.tensor(stat['std']).float())`
the error:
`FileNotFoundError: [Errno 2] No such file or directory: 'dataset/ETTh1/var_scaler_info.npz'`
was fixed. I thought data had been normalized in RevIN, and no regularisation or inverse transform in LTSF was required.
However, I got another error:
`FileNotFoundError: [Errno 2] No such file or directory: 'dataset/ETTh1/feature.npz'`

**Comment by hexiangdong2020** [comment]
I wrote a script to generate var_scaler_info.npz and feature.npz from ETTh1.csv:
`import pandas as pd
import numpy as np

# 读取CSV文件
df = pd.read_csv('dataset/ETTh1/ETTh1.csv')

# 将第一列"date"列转化为字符串类型的numpy列表
time_marker = pd.to_datetime(df['date'])
tod = time_marker.dt.hour * 60 + time_marker.dt.minute
dow = time_marker.dt.dayofweek
dom = time_marker.dt.day
doy = time_marker.dt.dayofyear
time_marker = np.vstack((tod, dow, dom, doy)).T

# 将其余列转化为浮点数类型的numpy二维数组
columns = ["HUFL", "HULL", "MUFL", "MULL", "LUFL", "LULL", "OT"]
var = df[columns].astype(float).to_numpy()

# 计算var各列的均值和标准差，并使用它们将var正则化
var_mean = np.mean(var, axis=0)
var_std = np.std(var, axis=0)
var = (var - var_mean) / var_std

print(var.shape)
print(time_marker.shape)

# 将var和time_marker保存在同一个文件feature.npz
np.savez('feature.npz', norm_var=var, norm_time_marker=time_marker)

# 将var的均值和标准差保存在var_scaler_info.npz
np.savez('var_scaler_info.npz', mean=var_mean, std=var_std)
`
And move the generated files to dataset/ETTh1/. It really works. 
However, I was unable to reproduce your paper's results at 96 length.
In your paper, MAE is 0.395 and MSE is 38.6.
In my experiment, MAE is 0.369 and MSE is 0.307, which is much lower.
So, how can I reproduce your results in your paper.
![image](https://github.com/user-attachments/assets/cc8f21fd-9574-4d02-90c5-b827d521214c)

**Comment by smilehanCN** [comment]
Thank you for your additional experiments, but your data processing process has data leakage issues: you use the mean and variance of all data, and most of works use the mean and variance of the training set. I have put the dataset I processed on [[Baidu Drive]](https://pan.baidu.com/s/18NKge4dsMIuGQFom7n2S2w?pwd=zumh). and the data processing code will be released soon.

And the results of baselines in Table 2 are from other published paper (iTransformer).
